### ISSUE TITLE
Big White Box when close to walls

### ISSUE THREAD

**Issue by Haczar** [cmbruns/gz3doom#105]
No idea what exactly triggers it but when there are tight corridors or close to a wall a big white box covers the front lower view taking up the hand, gun crosshair, down to the stats hud. It was during the second episode " The Shores of Hell" when walking close to the big red cross and other areas. I have not changed any settings in any of the options provided in the menu. Any help is appreciated

**Comment by Haczar** [comment]
also want to add when changing the option for use "shaders for lights" in the opengl options I get judder even if i revert the change.

**Comment by cmbruns** [comment]
Sounds like this might be the same as issue #103

**Comment by joukos** [comment]
I also have this problem very frequently, it seems like it might be related to map geometry (often in front of unopened doors) or rendering of it, but I noticed that when I pick up the invulnerability orb, the white box(es) appears, making it *very* hard to shoot stuff because you can't see anything behind it. It's like the front and back face of a viewing frustum went white for some reason.

I suspected it might have to do with the inverted colors or other HUD effects, but didn't find any option in the menus that would have an effect on it, tried pretty much toggling all of them while the white box was there.

Otherwise it runs great and is fun, and this is the only issue that is actually not-so-minor as the bright, white flashes break immersion and picking up the invulnerability makes the game basically unplayable for its duration.

I tested using DK2, 0.8 runtime and an old HD5750 with the latest drivers.

**Comment by joukos** [comment]
I guess it might make sense that when the invulnerability effects inverts colors, it fails with the transparency of the two, but whatever the underlying reason, might it help if the invert effect was not applied to the gun and status graphic at least for the power-up problem? It's not that big of a deal really though, since the orbs are pretty scarce.

When it happens seemingly randomly or often it's usually in complex maps, I noticed this happening with TNT:Evilution wad more frequently than vanilla Doom/Doom2, for example here was one spot where I consistently got white flashes in many places just walking around: http://imgur.com/99OI4hm  , in that map there's also some funny design like a force field that looks a bit glitched when it lowers and all sorts of confusing things going on overall.

It sometimes seemed I can just move my head back a bit to "get out" of the white but I couldn't get very consistent results with adjusting the head distance, sometimes minor head movements make it come and go depending which way you look.

**Comment by cmbruns** [comment]
One example of the "white box" glitch appears in E1M9 near the switch at "D" on the map at http://doom.wikia.com/wiki/E1M9:_Military_Base_%28Doom%29

The white box glitch only appears if I approach sufficiently close to the wall with the switch. As if there is a line on the floor past which the glitch can occur.

Also, the white box glitch only appears if my gaze is directed such that the point on the wall directly south of my viewpoint is visible. That is, I need to be looking generally toward the wall, enough that the relative wall center is in my field of view. If look up, down, left, or right, sufficiently far from looking directly at the wall, the glitch disappears.

I assume there is some sort of OpenGL state problem going on here. That white square represents the HUD area, and it is created in two passes. First, the non-3D portions of the scene are rendered into an offscreen framebuffer. Second, the contents of that framebuffer are rendered to an in-world quad in the 3D scene. In principle, the glitch could be created at either of these steps. But I suspect the second step more, because I do not recall seeing artifacts like this before I implemented the in-world quad HUD last autumn.

![screenshot_doom_20160406_104836](https://cloud.githubusercontent.com/assets/2649705/14320986/541e67da-fbe5-11e5-899c-a384fc5c445f.png)
![screenshot_doom_20160406_104834](https://cloud.githubusercontent.com/assets/2649705/14320990/582a2922-fbe5-11e5-961f-dead7f38c569.png)
![e1m9dots_white_box](https://cloud.githubusercontent.com/assets/2649705/14321125/ea034446-fbe5-11e5-959a-5b6b015466eb.png)

**Comment by cmbruns** [comment]
I got the E1M9 switch glitch to go away by adding a gl_RenderState.Apply() call, to realize the current OpenGL state settings, just before rendering the HUD quad.

Now I need to find an invulnerability sphere, and see how that works.

**Comment by cmbruns** [comment]
Fix in previous comment did not repair the opacity in invulnerability mode, so I had to create a separate fix for that. The weapon sprite intensities are not inverted in invulnerability mode now for some reason, but that's a minor minor bug compared to these other display glitches.

**Comment by cmbruns** [comment]
Fixed in revision da1ca78b0f1492d12b9e83f2dfeae7c522335634 for release 1.8.10_d
