### ISSUE TITLE
Screen Stretched Across Monitors

### ISSUE THREAD

**Issue by HelenSkelter** [cmbruns/gz3doom#65]
The last 2 versions get displaced/cutoff on the rift. It looks like black bars are being added to both sides and the window (It's in fullscreen) will extend onto my main monitor.
I have resolutions set correctly at 1920x1080 on both monitors, however if I remove the resolution and "+oculardium_optimosa" lines from the .bat then the window will be the right size but each eye will the entire "Oculus Double" view. So I'll have 4 separate views total that way, 2 in each eye.

Screenshots of error: http://imgur.com/a/mdcMC

DK2
Sapphire R9 290x 
Windows 8.1 
F.lux disabled 
DirectX 11

**Comment by cmbruns** [comment]
This issue is a follow up to the reddit discussion at 
https://www.reddit.com/r/oculus/comments/32cday/gz3doom_release_adds_positional_tracking_on_dk2/cqaecvu

Is your Rift configuration set to "extended mode" rather than "direct to rift"?

I notice you use an AMD GPU (where I usually use nvidia). Are you using Eyefinity to create one large virtual monitor?

**Comment by HelenSkelter** [comment]
Yes, it's set to extended. No, I am not using Eyefinity.

**Comment by cmbruns-hhmi** [comment]
@HelenSkelter OK. Let's keep thinking... You said that the last two versions have this problem. I assume you mean that versions 1.8.6_k and 1.8.6_l have the problem. Does this imply that you tried 1.8.6_j, and it was OK? Or are k and l(el) the only two you have tried?

**Comment by cmbruns** [comment]
I'm closing this issue because extended mode is now obsolete.
